export const MOROCCAN_CITIES = [
  "Agadir",
  "Al Hoceima",
  "Asilah",
  "Beni Mellal",
  "Berkane",
  "Berrechid",
  "Casablanca",
  "Chefchaouen",
  "Dakhla",
  "El Jadida",
  "Errachidia",
  "Essaouira",
  "Fès",
  "Figuig",
  "Guelmim",
  "Ifrane",
  "Kénitra",
  "Khemisset",
  "Khouribga",
  "Laâyoune",
  "Larache",
  "Marrakech",
  "Meknès",
  "Mohammédia",
  "Nador",
  "Ouarzazate",
  "Oujda",
  "Rabat",
  "Safi",
  "Salé",
  "Sefrou",
  "Settat",
  "Sidi Kacem",
  "Tanger",
  "Tantan",
  "Taroudant",
  "Taza",
  "Témara",
  "Tétouan",
  "Tiznit",
] as const;

export const NEED_CATEGORIES = [
  "Nettoyage",
  "Aide scolaire",
  "Don urgent",
  "Accompagnement",
  "Bricolage",
  "Transport",
  "Autre",
] as const;

export type MoroccanCity = typeof MOROCCAN_CITIES[number];
export type NeedCategory = typeof NEED_CATEGORIES[number];
